language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install pep8
  - pip install -r requirements.txt
# command to run tests
script:
  - pep8 fglib
  - nosetests

